# Generated by Django 5.1.4 on 2025-01-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
